// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqtofiqbqhwklhkltfkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxdG9maXFicWh3a2xoa2x0ZmtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MzgxMjgsImV4cCI6MjA2MTQxNDEyOH0.WhCxcl2mUqDOIhE8UluhKQo2VDpQQ_fYvTNhs6SgvhU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);